### ISSUE TITLE
Fails to rebuild for electron 28+ (v8 12+)

### ISSUE THREAD

**Issue by chrbongardt** [santigimeno/node-pcsclite#101]
V8 v12 brings some breaking changes to the ObjectTemplate::SetAccessor signature. NAN is working on a fix: [https://github.com/nodejs/nan/pull/966](https://github.com/nodejs/nan/pull/966). 

As soon as the fixing NAN version is released I will open a PR. Just wanted to have this tracked. 

Thanks!

**Comment by chrbongardt** [comment]
Done, I just created PR #102 that should fix this.

**Comment by chrbongardt** [comment]
While this get's merged and released by @santigimeno you can use my branch by doing 
`npm i git@github.com:chrbongardt/node-pcsclite.git#master`  

- Tested up to electron v29!

**Comment by rkeithhill-keysight** [comment]
Huh, nan 2.19.0 does not fix this issue for Electon 28 builds. I still get:
```
'v8::ObjectTemplate::SetAccessor': no overloaded function could convert all the argument types
```

**Comment by crudolf** [comment]
@santigimeno would be awesome to have new release here ❤️

**Comment by ayZagen** [comment]
the mentioned fix does not work with electron 30+. It seems unlikely but I hope we see a new version with n-api instead of nan.
